---
title: "R Notebook"
output: html_notebook
---

```{r}
# remove global environment
rm(list = ls())

library(rtweet)  # twitter library 
library(lubridate)
library(dplyr)

```

need only be done once after caching

```{r}
appname <- "yourappname"
api_key <- "yourapikey"
api_secret_key <- "yourapisecretkey"
access_token <- 'youraccesstoken'
access_token_secret <- 'youraccesstokensecret'

## authenticate via web browser
token <- create_token(
  app = appname,
  consumerKey <- api_key,
  consumerSecret <- api_secret_key,
  accessToken <- access_token, 
  accessTokenSecret <- access_token_secret)

```
 
 API call to get trump timeline
 
```{r}

## token creation that authenticates access to tweets done only once across all applications!!!
## check to see if the token is loaded. 
get_token()

# get most recent 3000 tweets 
tweets <- get_timelines(c ( '@realDonaldTrump'), n = 3000, retryonratelimit =TRUE)
save_as_csv(tweets, 'trump-timeline.csv', prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")

```

Read twitter data saved in csv

```{r}
library(readr) # different from default
datafile<- 'trump-timeline.csv'
tweets <- read_csv(datafile)
head(tweets)
```

Excel

```{r}
library(readxl)
tweets <- read_excel('trumptweet.xlsx', skip=0)
head(tweets)
```

Exploratory

```{r}
library(ggplot2)

# tweets by year (line chart)
tweetsByMonYear <- function (df, mtitle) {
ggplot(data = df, aes(month(created_at, label=TRUE, abbr=TRUE),
  group=factor(year(created_at)), 
  color=factor(year(created_at))))+
  geom_line(stat="count") +
  geom_point(stat="count") +
  labs(x="", colour="Year") +
  xlab("") + ylab("") +
  ggtitle(mtitle) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
               plot.title = element_text(hjust = 0.5, size=10, face="bold"))

}

tweetsByMonYear(tweets, 'TrumpTweets by Month and Year')
```


```{r}
tweetsOverMonths <- function (df, maintitle='') {
  ggplot(df, aes(x = month(created_at, label = TRUE))) +
    geom_bar(aes(fill = ..count..), show.legend=FALSE) +
    xlab("") + ylab("") + 
    ggtitle(maintitle) +
    geom_text(stat='count', aes(label=..count..), vjust=-1, size=2.5)+ #count labels
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
              plot.title = element_text(hjust = 0.5, size=10, face="bold")) # center 
}
tweetsOverMonths(tweets, 'Tweets over Months')
```

Sentiment analysis

```{r}
library(syuzhet)
library(plotly)

cleanText <- function (df) {
  # Convert tweets to ASCII to trackle strange characters
  tweet_text <- iconv(df$text, from="UTF-8", to="ASCII", sub="")

  tweet_text<-gsub('(RT|via)((?:\\b\\W*@\\w+)+)', '', tweet_text) # remove retweets
  tweet_text<-gsub('@\\w+', '', tweet_text) # remove mentions
  tweet_text<-gsub('[[:punct:]]', '',  tweet_text) # remove punctuation
  tweet_text<-gsub('[[:digit:]]', '', tweet_text)  # remove numbers
  tweet_text<-gsub('http\\w+', '', tweet_text)     # remove html links
  tweet_text<-gsub('[ \t]{2,}', '', tweet_text)    # remove unnecessary spaces
  tweet_text<-gsub('^\\s+|\\s+$', '', tweet_text)
  tweet_text<-gsub('<.*>', '', enc2native(tweet_text)) # remove emojis 
  tweet_text<-tolower(tweet_text)
  return (tweet_text)
}

plotSentiment <- function (df, mtitle='') {

  # data cleaning
  tweet_text <- cleanText(df)
  
  # get the emotions using the NRC dictionary
  df_sentiment<-get_nrc_sentiment((tweet_text))
  sentimentscores<-data.frame(colSums(df_sentiment[,]))

  names(sentimentscores) <- "Score"
  sentimentscores <- cbind("sentiment"=rownames(sentimentscores),sentimentscores)
  rownames(sentimentscores) <- NULL

  ggplot(data=sentimentscores,aes(x=sentiment,y=Score))+
    geom_bar(aes(fill=sentiment),stat = "identity")+
    theme(legend.position="none")+
    xlab("")+ylab("")+
    ggtitle(mtitle)+
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
               plot.title = element_text(hjust = 0.5, size=10, face="bold"))
  
}
  
plotSentiment(tweets, 'total sentiment')

```

wordcloud

```{r}
library(wordcloud2)
library(tidytext)
library(stringr)

wordCloud <- function (df, exclude) {
  
  #Unnest the words - code via Tidy Text
  hmtTable <- df %>% 
    unnest_tokens(word, text)
  
  #remove stop words 
  data(stop_words)
  hmtTable <- hmtTable %>%
    anti_join(stop_words)
  
  #do a word count
  hmtTable <- hmtTable %>%
    count(word, sort = TRUE) 
  
  hmtTable <-hmtTable %>%
    filter(!word %in% exclude) %>%                #Remove unwanted words
    filter(!str_detect(word, "http\\w+")) %>%     # remove links
    filter(!str_detect(word, "[[:punct:]]")) %>%   # remove punctuation
    filter(!str_detect(word, "[[:digit:]]")) %>%       # numbers
  filter(!str_detect(word, "(RT|via)((?:\\b\\W*@\\w+)+)")) # retweets
  
  wordcloud2(hmtTable, size=0.7) #create wordcloud
}

wordCloud(tweets,  c('t.co'))
```

Enagement

```{r}

df1 <- tweets
# number of mentions
 df1.mentions <- 0
if("mentions_user_id" %in% colnames(df1)) {
  df1.mentions <-sum(df1$mentions_user_id != '') 
}

#how many times this Tweet has been liked by Twitter users
df1.fav_count <- sum(df1$favorite_count)

#Number of times this Tweet has been retweeted 
df1.retweet_cnt <- sum(df1$retweet_count)

#number of followers this account currently has
 df1.follows_cnt <- 66068545
if("followers_count" %in% colnames(df1)) {
  df1.follows_cnt <-  df1[1, 'followers_count']
}


s <- data.frame("index" = c(1),
                "account" = c("@realDonaldTrump"),
                "mentions" = c(df1.mentions),
                "favorites" = c(df1.fav_count),
                "retweets" = c(df1.retweet_cnt),
                "followers" = c(df1.follows_cnt))
 print(s)

```

Tweet sources
```{r}

plotSource <- function (df) {
  colors=rainbow(n=12)
  counts = table(df$source)  # get counts
  
  barplot(counts, axisnames = FALSE,
          legend=TRUE, 
          ylim=c(0,14000), 
          col = colors,
          #col=c('deeppink', 'darkviolet','deeppink4', 'deepskyblue', 'forestgreen', 'gold','gold4' ),
          #args.legend=list("topleft",bty = "n")
          args.legend=list(x=ncol(df) +9, bty = "n")
          
          )
  
}

plotSource (tweets)
```


Comparison of the number re-tweets to original tweets. Indication of user engagement.

```{r}

plotRetweets <- function (df, maintitle='') {
ggplot(data = df, aes(x = as.numeric(created_at), fill = is_retweet)) +
  geom_histogram(bins=40)+
  xlab("") + ylab("") + 
  ggtitle(maintitle) +
  scale_fill_manual(values = c("deepskyblue3", "deepskyblue4"), name = "Retweet")
}

plotRetweets (tweets, 'Tweets vs retweets')

```

